const styles: { [key: string]: React.CSSProperties } = {
  pageContainer: {
    position: "relative",
    width: "100%",
    height: "100vh",
    overflow: "hidden",
  },
  mapContainer: {
    width: "100%",
    height: "100%",
  },
  infoPanel: {
    position: "absolute",
    top: "20px",
    left: "20px",
    background: "white",
    padding: "16px",
    borderRadius: "8px",
    fontSize: "14px",
    width: "280px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
    zIndex: 1000,
  },
  viewToggleButton: {
    position: "absolute",
    top: "20px",
    right: "100px",
    background: "white",
    border: "1px solid #ddd",
    borderRadius: "4px",
    padding: "8px 12px",
    fontSize: "14px",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    zIndex: 1000,
  },
  progressBarContainer: {
    width: "100%",
    height: "6px",
    backgroundColor: "#f0f0f0",
    borderRadius: "3px",
    marginBottom: "10px",
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    borderRadius: "3px",
    transition: "width 0.5s ease-in-out",
  },
  distanceInfo: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: "5px",
  },
  distance: {
    fontSize: "18px",
    fontWeight: "600",
  },
  totalDistance: {
    fontSize: "14px",
    color: "#666",
    marginLeft: "5px",
  },
  percentage: {
    fontSize: "14px",
    fontWeight: "500",
  },
  divider: {
    height: "1px",
    backgroundColor: "#eee",
    width: "100%",
    margin: "15px 0",
  },
  locationInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
  },
  locationLabel: {
    fontSize: "12px",
    color: "#666",
    marginBottom: "4px",
  },
  currentCity: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#e91e63",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  distanceToNext: {
    fontSize: "12px",
    color: "#666",
    marginTop: "4px",
    fontStyle: "italic",
  },
  nextLocationContainer: {
    marginTop: "5px",
  },
  nextCity: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#2196f3",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  completedBadge: {
    backgroundColor: "#e8f5e9",
    color: "#2e7d32",
    padding: "8px 12px",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "500",
    textAlign: "center",
    marginTop: "15px",
  },
};

export default styles;
