import React from "react";
import { SystemStyleObject } from "@styled-system/css";
import * as VP from "@opr-finance/api-definitions";
import { DefaultFormProps } from "@opr-finance/component-forms";
import { T_WithdrawalRules } from "@opr-finance/utils";
export type T_StyledWithdrawProps = {
    styleConfig: {
        id?: string;
        creditRaiseContainer: SystemStyleObject;
        creditRaiseTitle: SystemStyleObject;
        creditRaiseWrapper: SystemStyleObject;
        creditRaiseInputColumn: SystemStyleObject;
        creditRaiseInputLabel?: SystemStyleObject;
        creditRaiseInputSectionWrapper?: SystemStyleObject;
        creditIncreaseInputRow: SystemStyleObject;
        creditRaiseInputWrapper: SystemStyleObject;
        creditRaiseInput: SystemStyleObject;
        creditRaiseEuroSign: SystemStyleObject;
        greenButtonStyles: SystemStyleObject;
        disabledButtonStyles: SystemStyleObject;
        buttonFontStyles: SystemStyleObject;
        creditRaiseInfoColumn: SystemStyleObject;
        creditRaiseText: SystemStyleObject;
        errorMessage: SystemStyleObject;
        rulesContainer: SystemStyleObject;
        notEligibleText: SystemStyleObject;
        withdrawalSentMessageText?: SystemStyleObject;
        buttonInfo: SystemStyleObject;
    };
    max: number;
    onSubmit: (value: number) => void;
    isWithdrawn: boolean;
    unit: string;
    isLoading?: boolean;
    availableCreditLimit: number | undefined;
    accountState: VP.components["schemas"]["AccountState"] | undefined;
    overdueDays: number | undefined;
    unpaidAmount: number | undefined;
    isIbanMissing?: boolean | undefined;
    blockedStatus?: boolean;
    kycOverdue?: boolean;
    withdrawalRules: T_WithdrawalRules;
    isLoanPage?: boolean;
    messages: {
        title: string;
        inputLabel: string;
        inputPlaceholder: string;
        buttonText: string;
        buttonInfo: string;
        info1Text: string;
        info2Text?: string;
        info3Text: string;
        info4Text: string;
        withdrawSentMessage: string;
        withdrawAlertText1: string;
        withdrawAlertText2: string;
        euroCurrency: string;
        notEligibleText: string;
        withdrawOverdueInvoice: string;
        withdrawAvailableCreditTooSmall: string;
        withdrawNotAbleToMakeWithdrawal: string;
        withdrawNoIbanNumber: string;
        withdrawBlockedByKyc?: string;
    };
    ref?: any;
} & DefaultFormProps<T_WithdrawAmount>;
export type T_WithdrawAmount = {
    withdrawAmount: string;
};
export declare function StyledWithdraw(props: T_StyledWithdrawProps): React.JSX.Element;
