export const interestTypes = [
  "LoanAdjustmentInterestTransaction",
  "StatementInterestBeforeFirstStatementTransaction",
  "StatementInterestTransaction",
];

export const allowedPaymentTransactionTypesFiNl = [
  "PayStatementAmortizationTransaction",
  "OverPaymentReducePrincipalTransaction",
  "PayStatementInterestBeforeFirstStatementTransaction",
  "PayStatementInterestTransaction",
  "PayStatementAdjustmentInterestTransaction",
  "PayStatementLatePaymentInterestTransaction",
  "PayStatementAdjustmentStartupFeeTransaction",
  "PayStatementStartupFeeTransaction",
  "PayStatementTrancheStartupFeeTransaction",
];

export const allowedPaymentTransactionTypesSe = [
  ...allowedPaymentTransactionTypesFiNl,
  "PayStatementAdjustmentLatePaymentInterestTransaction",
  "PayStatementReminderFeeTransaction",
  "PayStatementAdjustmentReminderFeeTransaction",
];

export const notInStatementTransactionsTypes = [
  ...allowedPaymentTransactionTypesSe,
  "PayStatementAdjustmentCollectionFeeTransaction",
  "PayStatementAdjustmentDirectDebitFeeTransaction",
  "PayStatementAdjustmentEInvoiceFeeTransaction",
  "PayStatementAdjustmentLatePaymentFeeTransaction",
  "PayStatementAdjustmentStatementFeeTransaction",
  "PayStatementCollectionFeeTransaction",
  "PayStatementDirectDebitFeeTransaction",
  "PayStatementEInvoiceFeeTransaction",
  "PayStatementFeeTransaction",
  "PayStatementLatePaymentFeeTransaction",
  "PayStatementRoundingTransaction",
  "PayStatementInsurancePremieFullTransaction",
  "PayStatementInsurancePremieLifeTransaction",
  "PayStatementAdjustmentInsurancePremieFullTransaction",
  "PayStatementAdjustmentInsurancePremieLifeTransaction",
  "PayTrancheAdministrativeFeeTransaction",
  "PayPrepaymentTransaction",
  "PayUnpaidAmountFromStatementTransaction",
  "UnpaidAmountFromStatementTransaction",
  "VirtualCuringAmortizationTransaction",
  "VirtualPayCuringAmortizationTransaction",
  "VirtualPayCuringFeeTransaction",
  "VirtualPayCuringInterestTransaction",
  "VirtualPayCuringInsuranceTransaction",
  "PayServiceFeeBeforeFirstStatementTransaction",
  "PayServiceFeeTransaction",
  "PayAdjustmentServiceFeeTransaction",
  "PaySpecialLeasingFeeBeforeFirstStatementTransaction",
  "PayStatementPaymentPlanFeeTransaction",
  "PayStatementStartupFeeAmortizationTransaction",
  "PayStatementAdjustmentStartupFeeAmortizationTransaction",
  "PayStatementAdjustmentPaymentPlanFeeTransaction",
  "PayInstallmentSaleOfContractAmountTransaction",
  "RevertPayInstallmentSaleOfContractAmountTransaction",
  "PayInstallmentDownPaymentTransaction",
  "RevertPayInstallmentDownPaymentTransaction",
  "PayLeasingSaleOfContractExcludeVatAmountTransaction",
  "RevertPayLeasingSaleOfContractExcludeVatAmountTransaction",
  "PayLeasingSaleOfContractVatAmountTransaction",
  "RevertPayLeasingSaleOfContractVatAmountTransaction",
  "PayLeasingDownPaymentExcludeVatAmountTransaction",
  "RevertPayLeasingDownPaymentExcludeVatAmountTransaction",
  "PayLeasingDownPaymentVatAmountTransaction",
  "RevertPayLeasingDownPaymentVatAmountTransaction",
];
