import { SystemStyleObject } from "@styled-system/css";
export type BoxCssProps = {
    isCentered?: boolean;
    flexDirection?: "row" | "column";
};
export type TitleCssProps = {
    isTextCentered?: boolean;
};
export type LargeButtonCssProps = {
    isLogin?: boolean;
};
export declare function bodyTitle(props?: TitleCssProps): SystemStyleObject;
export declare function box(props?: BoxCssProps): SystemStyleObject;
export declare function contentBox(): SystemStyleObject;
export declare function headerContainer(): SystemStyleObject;
export declare function headerContent(): SystemStyleObject;
export declare function headerTitle(): SystemStyleObject;
export declare function largeButton(props?: LargeButtonCssProps): SystemStyleObject;
export declare function loginButtonTextStyle(): SystemStyleObject;
export declare function pageTitle(props?: TitleCssProps): SystemStyleObject;
export declare function footerContainer(): SystemStyleObject;
export declare function body(): SystemStyleObject;
export declare function userInfoContent(): SystemStyleObject;
export declare function userInfoTitle(): SystemStyleObject;
export declare function textItem(): SystemStyleObject;
export declare function secondaryButton(): SystemStyleObject;
export declare function secondaryButtonText(): SystemStyleObject;
export declare function bodyLabel(): SystemStyleObject;
export declare function bodyWarning(): SystemStyleObject;
export declare function mobilePageTitle(): SystemStyleObject;
export declare function textField(): SystemStyleObject;
export declare function select(): SystemStyleObject;
export declare function checkbox(): SystemStyleObject;
export declare function checkboxDisabled(): SystemStyleObject;
export declare function checkboxText(): SystemStyleObject;
export declare function button(): SystemStyleObject;
export declare function buttonText(): SystemStyleObject;
export declare function formError(): SystemStyleObject;
export declare function link(): SystemStyleObject;
export declare function headerLink(): SystemStyleObject;
export declare function sideBox(): SystemStyleObject;
export declare function breadcrumbBox(): SystemStyleObject;
export declare function inlineBox(): SystemStyleObject;
export declare function sideTitle(): SystemStyleObject;
export declare function sideLink(): SystemStyleObject;
export declare function breadcrumbTitle(): SystemStyleObject;
export declare function buttonInfo(): SystemStyleObject;
export declare function buttonCancel(): SystemStyleObject;
export declare function buttonSubmit(): SystemStyleObject;
export declare function buttonSubmitDisabled(): SystemStyleObject;
export declare function buttonLogout(): SystemStyleObject;
export declare function buttonLoginAgain(): SystemStyleObject;
