import { Theme } from "./themeTypes";
import { ThemeTranslations } from "./translationKeys";

export const tourDeFranceTheme: Theme = {
  name: "Tour de France 2025",
  totalStages: 21,
  totalDistance: 3338.8,
  totalPoints: 3338.8,
  colors: {
    primary: "#facc15", // yellow
    background: "#fffefc",
    card: "#ffffff",
    text: "#1e293b",
    mutedText: "#64748b",
    border: "#e2e8f0",
    accent: "#facc15",
    button: "#facc15",
    secondary: "#facc15",
    textSecondary: "#facc15",
    success: "#facc15",
    warning: "#facc15",
    error: "#facc15"
  },
stages: [
  {
    name: "Lille Métropole → Lille Métropole",
    pointsRequired: 0,
    emoji: "🏁",
    description: "Etappi 1: Kierros Lillen ympäri",
    stageType: "tasainen",
    weather: "Aurinkoinen",
    location: "Lille, Ranska",
    color: "from-yellow-200 to-yellow-400",
  },
  {
    name: "Lauwin‑Planque → Boulogne‑sur‑Mer",
    pointsRequired: 184.9,
    emoji: "🌊",
    description: "Etappi 2: Pisin ja mäkinen sivutuulietappi",
    stageType: "mäkinen",
    weather: "Tuulinen",
    location: "Boulogne-sur-Mer, Ranska",
    color: "from-blue-200 to-blue-400",
  },
  {
    name: "Valenciennes → Dunkerque",
    pointsRequired: 394.0,
    emoji: "🚴",
    description: "Tasainen etappi Pohjois-Ranskan rannikolla",
    stageType: "tasainen",
    weather: "Pilvinen",
    location: "Dunkerque, Ranska",
    color: "from-indigo-200 to-indigo-400",
  },
  {
    name: "Amiens Métropole → Rouen",
    pointsRequired: 572.3,
    emoji: "⚡",
    description: "Tasainen etappi kohti Normandiaa",
    stageType: "tasainen",
    weather: "Vaihteleva",
    location: "Rouen, Ranska",
    color: "from-gray-200 to-gray-400",
  },
  {
    name: "Caen → Caen (ITT)",
    pointsRequired: 745.5,
    emoji: "⏱️",
    description: "33 km:n henkilökohtainen aika-ajo",
    stageType: "aika-ajo",
    weather: "Pilvinen",
    location: "Caen, Ranska",
    color: "from-cyan-300 to-cyan-500",
  },
  {
    name: "Bayeux → Vire Normandie",
    pointsRequired: 947.0,
    emoji: "🚣️",
    description: "Mäkinen etappi nousuineen Normandiassa",
    stageType: "mäkinen",
    weather: "Pilvinen",
    location: "Vire Normandie, Ranska",
    color: "from-green-300 to-green-500",
  },
  {
    name: "Saint‑Malo → Mûr‑de‑Bretagne Guerlédan",
    pointsRequired: 1141.0,
    emoji: "⛰️",
    description: "Mäkinen etappi, maali kukkulan huipulla",
    stageType: "mäkinen",
    weather: "Vaihteleva",
    location: "Mûr-de-Bretagne, Ranska",
    color: "from-lime-400 to-lime-600",
  },
  {
    name: "Saint‑Méen‑le‑Grand → Laval Espace Mayenne",
    pointsRequired: 1312.4,
    emoji: "🍃",
    description: "Tasainen sprinttietappi",
    stageType: "tasainen",
    weather: "Aurinkoinen",
    location: "Laval, Ranska",
    color: "from-amber-300 to-amber-500",
  },
  {
    name: "Chinon → Châteauroux",
    pointsRequired: 1486.5,
    emoji: "⚡",
    description: "Tasainen etappi, sivutuulet mahdollisia",
    stageType: "tasainen",
    weather: "Pilvinen",
    location: "Châteauroux, Ranska",
    color: "from-rose-300 to-rose-500",
  },
  {
    name: "Ennezat → Le Mont‑Dore (Puy de Sancy)",
    pointsRequired: 1649.8,
    emoji: "🏔️",
    description: "Vuoristomaali Massif Centralissa",
    stageType: "vuoristo",
    weather: "Tuulinen",
    location: "Le Mont-Dore, Ranska",
    color: "from-red-400 to-red-600",
  },
  {
    name: "Toulouse → Toulouse",
    pointsRequired: 1806.6,
    emoji: "🕒",
    description: "Tasainen kierros Toulousen ympäri",
    stageType: "tasainen",
    weather: "Aurinkoinen",
    location: "Toulouse, Ranska",
    color: "from-yellow-200 to-yellow-400",
  },
  {
    name: "Auch → Hautacam",
    pointsRequired: 1987.2,
    emoji: "🔺",
    description: "Vuoristomaali Hautacamissa",
    stageType: "vuoristo",
    weather: "Pilvinen",
    location: "Hautacam, Ranska",
    color: "from-blue-500 to-blue-700",
  },
  {
    name: "Loudenvielle → Peyragudes (TTT)",
    pointsRequired: 1998.1,
    emoji: "⏱️",
    description: "Vuoristoaika-ajo Peyragudeen",
    stageType: "aika-ajo",
    weather: "Vaihteleva",
    location: "Peyragudes, Ranska",
    color: "from-cyan-400 to-cyan-600",
  },
  {
    name: "Pau → Luchon‑Superbagnères",
    pointsRequired: 2180.7,
    emoji: "🟛",
    description: "Kuningasetappi Pyreneillä",
    stageType: "vuoristo",
    weather: "Myrsky",
    location: "Luchon-Superbagnères, Ranska",
    color: "from-violet-500 to-violet-700",
  },
  {
    name: "Muret → Carcassonne",
    pointsRequired: 2350.0,
    emoji: "🌿",
    description: "Mäkinen, aaltoileva maasto kohti Carcassonnea",
    stageType: "mäkinen",
    weather: "Pilvinen",
    location: "Carcassonne, Ranska",
    color: "from-green-400 to-green-600",
  },
  {
    name: "Montpellier → Mont Ventoux",
    pointsRequired: 2521.5,
    emoji: "🌋",
    description: "Huippumaali Mont Ventoux’lla",
    stageType: "vuoristo",
    weather: "Tuulinen",
    location: "Mont Ventoux, Ranska",
    color: "from-slate-400 to-slate-600",
  },
  {
    name: "Bollène → Valence",
    pointsRequired: 2681.9,
    emoji: "🌼",
    description: "Tasainen sprinttietappi Provencen halki",
    stageType: "tasainen",
    weather: "Aurinkoinen",
    location: "Valence, Ranska",
    color: "from-orange-300 to-orange-500",
  },
  {
    name: "Vif → Courchevel (Col de la Loze)",
    pointsRequired: 2853.4,
    emoji: "🧷",
    description: "Alppien huippumaali Col de la Lozessa",
    stageType: "vuoristo",
    weather: "Pilvinen",
    location: "Courchevel, Ranska",
    color: "from-teal-400 to-teal-600",
  },
  {
    name: "Albertville → La Plagne",
    pointsRequired: 2946.5,
    emoji: "🏔️",
    description: "Lyhyt vuoristoetappi La Plagneen",
    stageType: "vuoristo",
    weather: "Myrsky",
    location: "La Plagne, Ranska",
    color: "from-gray-500 to-gray-700",
  },
  {
    name: "Nantua → Pontarlier",
    pointsRequired: 3130.7,
    emoji: "🌲",
    description: "Mäkinen lähtö Alpeilta",
    stageType: "mäkinen",
    weather: "Vaihteleva",
    location: "Pontarlier, Ranska",
    color: "from-emerald-400 to-emerald-600",
  },
  {
    name: "Mantes‑la‑Ville → Paris (Champs‑Élysées)",
    pointsRequired: 3338.8,
    emoji: "🏆",
    description: "Seremoniallinen maali Pariisissa Montmartren kierroksella",
    stageType: "seremoniallinen",
    weather: "Aurinkoinen",
    location: "Pariisi, Ranska",
    color: "from-yellow-400 to-yellow-600",
  },
],

  weatherIcons: {
    Aurinkoinen: "☀️",
    Pilvinen: "☁️",
    Tuulinen: "💨",
    Vaihteleva: "🌤️",
    Myrsky: "⛈️",
  },

  stageColors: {
    tasainen: "text-yellow-600",
    mäkinen: "text-green-600",
    vuoristo: "text-red-600",
    "aika-ajo": "text-purple-600",
    seremoniallinen: "text-slate-600",
  },
  translations: {
    title: "Tour de France -haaste",
    teamTitle: "Peloton",
    dashboardTitle: "Tour de France -haaste",
    subtitle: "Peloton polkee yhdessä etappi etapilta!",
    selectThemeLabel: "Valitse teema",
    selectUserLabel: "Valitse pyöräilijä",
    selectUserPlaceholder: "Valitse oma profiilisi...",
    loginTitle: "Tervetuloa takaisin!",
    loginSubtitle: "Kirjaudu mukaan haasteeseen ja seuraa matkaa.",
    loginButton: "Liity pelotoniin",
    loginEmoji: "🚴‍♂️",
    stageLabel: "Etappi",
    stageSubtitle: "Stage {{number}} loop around {{location}}",
    nextStage: "Seuraava etappi",
    points: "Kilometrit",
    pointsToNext: "kilometriä seuraavaan etappiin",
    weather: "Sää",
    type: "Etappityyppi",
    stagesTitle: "Etapit",
    completed: "Valmis",
    current: "Nykyinen",
    upcoming: "Tulossa",
    leaderboardTitle: "🏆 Sijoitukset",
    weeklyGoal: "Viikon tavoite",
    kmRemaining: "{{km}} km jäljellä",
    tabs: {
      leaderboard: "Sijoitukset",
      weekly: "Viikon tilanne",
      quotes: "Kannustus",
    },
    submitQuoteTitle: "Kannusta pelotoniaasi",
    submitQuotePlaceholder: "Kirjoita kannustava viesti...",
    submitButton: "Lähetä",
    activeUsers: "Aktiivisia pyöräilijöitä",
    totalPointsLabel: "Yhteiskilometrit",
    goalLabel: "Tavoite: 3338 km",
    routeLabel: "Reitti: Tour de France 2025",
    loginNote: "Pisteet perustuvat liikutun matkan kilometreihin.",
    loading: "Ladataan...",
    error: "Tapahtui virhe.",

    // Navbar translations
    navbar: {
      title: "TOUR DE FRANCE",
      statistics: "Tilastot",
      climbers: "Pyöräilijät",
      loadingClimbers: "Ladataan pyöräilijöitä",
      errorLoadingClimbers: "Virhe pyöräilijöiden haussa",
      logout: "Kirjaudu ulos",
      ownProfile: "Oma profiili",
      failedToFetchUsers: "Käyttäjien lataaminen epäonnistui",
    },

    // WeeklyProgressBar translations
    weeklyProgressBar: {
      weeklyGoal: "Viikon tavoite",
      remaining: "jäljellä",
      goalAchieved: "Viikkotavoite saavutettu!",
      kmPerPerson: "km/hlö",
      errorLoadingData: "Virhe tietojen lataamisessa",
    },

    // Reactions translations
    reactions: {
      failedToLoad: "Reaktioiden lataaminen epäonnistui",
      failedToSave: "Reaktion tallentaminen epäonnistui",
      addReaction: "Lisää reaktio",
    },

    // ActivityForm translations
    activityForm: {
      noActivitiesFound: "Aktiviteetteja ei löytynyt.",
      bonusCalculated: "bonukset laskettu mukaan",
      bonus: "Bonus",
    },

    // Leaderboard translations
    leaderboard: {
      title: "Sijoitukset",
      rankings: "Tulokset",
      position: "Sija",
      totalDistance: "Yhteensä",
      noActivities: "Ei suorituksia",
      goldMedal: "Kultamitali",
      silverMedal: "Hopeamitali",
      bronzeMedal: "Pronssimitali",
    },

    // WeeklyProgress translations
    weeklyProgress: {
      title: "Viikon tilanne",
      thisWeek: "Tämä viikko",
      weeklyRanking: "Viikon ranking",
      completed: "Suoritettu",
      remaining: "Jäljellä",
      dailyTarget: "Päivätavoite",
      weeklyTarget: "Viikkotavoite",
      daysAgo: "päivää sitten",
      position: "Sija",
    },

    // ActivityFeed translations
    activityFeed: {
      title: "Viimeisimmät suoritukset",
      recentActivities: "Tuoreimmat aktiviteetit",
      noActivities: "Ei aktiivisuuksia saatavilla",
      addedActivity: "lisäsi suorituksen",
      completedWorkout: "suoritti treenin",
      timeAgo: "sitten",
      showComments: "Näytä kommentit",
      hideComments: "Piilota kommentit",
    },

    // General UI translations
    ui: {
      edit: "Muokkaa",
      delete: "Poista",
      cancel: "Peruuta",
      save: "Tallenna",
      confirm: "Vahvista",
      close: "Sulje",
      next: "Seuraava",
      previous: "Edellinen",
      viewProfile: "Näytä profiili",
      backToHome: "Etusivu",
    },

    // PersonalInsights translations
    insights: {
      title: "Omat tilastot",
      overview: "Yleiskatsaus",
      activity: "Suoritukset",
      totalActivities: "Suoritukset",
      totalHours: "Tunnit",
      totalKm: "Kilometrit",
      weeklyKm: "Viikko ka",
      currentStreak: "Nykyinen putki",
      longestStreak: "Pisin putki",
      days: "päivää",
      mostFrequentActivity: "Suosituin laji",
      personalStatistics: "Henkilökohtaiset tilastot",
      avgDuration: "Keskim. kesto",
      avgDistance: "Keskim. matka",
      mins: "min",
      km: "km",
      activityBreakdown: "Aktiviteettijakauma",
      times: "kertaa",
      addActivitiesToSee: "Lisää aktiviteetteja nähdäksesi tilastot.",
    },

    // Comments translations
    comments: {
      addComment: "Lisää kommentti",
      placeholder: "Kirjoita kommentti...",
      charactersLeft: "merkkiä jäljellä",
      send: "Lähetä",
      sending: "Lähetetään...",
      noComments: "Ei kommentteja vielä.",
      showComments: "Näytä kommentit",
      hideComments: "Piilota kommentit",
      loadingComments: "Ladataan",
    },

    // Pagination translations
    pagination: {
      previous: "Edellinen",
      next: "Seuraava",
      page: "Sivu",
      of: "/",
    },

    // Modal translations
    modal: {
      confirmDelete: "Vahvista poisto",
      confirmDeleteActivity: "Haluatko varmasti poistaa tämän suorituksen?",
      activityLabel: "Laji",
      dateLabel: "Päivämäärä",
      durationLabel: "Kesto",
      areYouSure: "Oletko varma?",
    },

    // AllTime insights translations
    allTime: {
      title: "Kaikkien aikojen tilastot",
      bestKmDay: "Eniten kilometrejä",
      longestWorkout: "Pisimmät treenit",
      currentStreak: "Nykyinen putki",
      loadingStats: "Ladataan tilastoja...",
      mostKm: "km",
      longestWorkouts: "min",
      currentStreakDays: "päivää",
      since: "Alkaen",
      bonusIncluded: "bonukset laskettu mukaan",
    },

    // User insights translations
    userInsights: {
      title: "Ladataan tilastoja...",
      todayVsLastWeek: "Tänään vs. viime viikko",
      weekComparison: "Viikkovertailu",
      kmTodayLastWeek: "Km tänään/viime viikko",
      activitiesTodayLastWeek: "Aktiviteetit tänään/viime viikko",
      totalKmThisLastWeek: "Yhteensä km tämä/viime viikko",
      activitiesThisLastWeek: "Aktiviteetit tämä/viime viikko",
      weekOverWeekComparison: "Viikkojen välinen vertailu",
      dailyComparison: "Päivittäinen vertailu",
      change: "muutos",
      noDataAvailable: "Ei tietoja saatavilla",
    },

    // PaceProjection translations
    paceProjection: {
      title: "Vauhtiennusteet",
      fullHistoryLabel: "Koko historia",
      fullHistoryDesc:
        "Perustuu koko haasteen aikana kertyneeseen keskimääräiseen vauhtiin.",
      recentLabel: "Viimeaikaiset",
      recentDesc: "Perustuu viimeisen 4 viikon aikana kertyneeseen vauhtiin.",
      weeklyLabel: "Viikon",
      weeklyDesc: "Perustuu viimeisimmän seitsemän päivän tahtiin.",
      requiredLabel: "Vaadittu",
      requiredDesc: "Vaadittu vauhti tavoitepäivään mennessä.",
      pacePerPerson: "Vauhti / hlö",
      estimatedCompletion: "Arvioitu valmistuminen",
      differenceFromTarget: "Ero tavoitteesta",
      exactly: "Täsmällisesti",
      daysLate: "päivää myöhässä",
      daysEarly: "päivää etuajassa",
      kmPerWeek: "km/vko",
      noData: "Ei tietoa",
    },

    // Records/Statistics translations
    records: {
      title: "Ennätykset",
      currentRecords: "Nykyiset ennätykset",
      mostKmInDay: "Eniten kilometrejä päivässä",
      longestWorkout: "Pisin treeni",
      longestStreak: "Pisin urheiluputki",
      startingFrom: "Alkaen",
      noDataAvailable: "Ei tietoja saatavilla",
      loadingRecords: "Ladataan ennätyksiä...",
      weeksBest: "Viikon parhaat",
      mostPopularSports: "Viikon suosituimmat",
      longestWorkoutOfWeek: "Viikon pisin treeni",
      weeklyTopPerformers: "Viikon ahkerimmat",
      performancesThisWeek: "suoritusta tällä viikolla",
      kmThisWeek: "km tällä viikolla",
      noPerformancesYet: "Ei vielä suorituksia",
    },

    // Weekly activity translations
    weeklyActivity: {
      title: "Viikkoaktiivisuus",
      weeksCalculated: "Viikot laskettu maanantaista sunnuntaihin",
      mondayToSunday: "Viikot laskettu maanantaista sunnuntaihin",
      sport: "Laji",
      thisWeek: "Tämä viikko",
      lastWeek: "Viime viikko",
      total: "Yhteensä",
      times: "kertaa",
      time: "kerta",
    },

    // Challenge closed translations
    challengeClosed: {
      newChallengeStarts: "Uusi haaste starttaa pian",
      detailsWillBeReleased: "Yksityiskohdat julkaistaan pian",
      prepareToBe:
        "valmistaudu inspiroitumaan ja lähtemään mukaan unohtumattomalle seikkailulle!",
      inspired: "inspiroituneeksi",
    },
    // CommentAndReactionView translations
    commentReactionView: {
      failedToLoadReactionsOrComments:
        "Reaktioiden tai kommenttien lataaminen epäonnistui.",
      failedToLoadComments: "Kommenttien lataaminen epäonnistui.",
    },

    // UserProfile translations
    userProfile: {
      failedToFetchUser: "Käyttäjätietojen lataaminen epäonnistui",
      failedToDeleteActivity: "Suorituksen poistaminen epäonnistui",
      failedToAddActivity: "Suorituksen lisääminen epäonnistui",
      failedToUpdateActivity: "Suorituksen päivittäminen epäonnistui",
      loginRequired: "Kirjautuminen vaaditaan",
      onlyLoggedInUsersCanView:
        "Vain kirjautuneet käyttäjät voivat tarkastella profiileja.",
      backToHome: "Takaisin kotiin",
      userNotFound: "Käyttäjää ei löytynyt",
      userAvatar: "Käyttäjän avatar",
      you: "Sinä",
      meters: "kilometriä",
      distance: "matkaa",
      km: "km",
      performances: "Suoritukset",
      statistics: "Tilastot",
      addPerformance: "Lisää suoritus",
      updatePerformance: "Päivitä suoritus",
      submissionClosed:
        "Suoritusten lisääminen on suljettu, koska haaste on päättynyt.",
      activityType: "Laji",
      selectActivity: "Valitse laji",
      specifyActivity: "Tarkenna laji",
      enterActivityName: "Kirjoita mikä laji",
      duration: "Kesto (minuutit)",
      date: "Päivämäärä",
      noBonus: "Ei bonuksia",
      perfectWeatherConditions: "Täydelliset sääolosuhteet",
      groupActivity: "Ryhmäaktiviteetti",
      wholeTeamTogether: "Koko tiimi mukana",
      canViewStats:
        "Voit tarkastella {username}:n tilastoja, mutta vain omat suoritukset ovat muokattavissa.",
      addActivityForUser: "Lisää suoritus käyttäjälle {username}",
    },

    // SubmitQuote translations
    submitQuote: {
      pleaseEnterQuote: "Ole hyvä ja kirjoita lainaus!",
      quoteSubmittedSuccessfully: "Lainaus lähetetty onnistuneesti!",
      failedToSubmitQuote: "Lainauksen lähettäminen epäonnistui",
      submitting: "Lähetetään...",
    },

    // Quotes translations
    quotes: {
      noQuotesAvailable: "Ei kannustuksia vielä saatavilla.",
      couldNotLoadQuotes: "⚠️ kannustuksia lataaminen epäonnistui.",
      loadingQuote: "Ladataan kannustuksia...",
    },

    // OverviewCards translations
    overviewCards: {
      soFar: "Tähän mennessä",
      weeklyGoal: "Viikon tavoite",
      person: "hlö",
      timeRemaining: "Aikaa jäljellä",
      days: "päivää",
    },

    // PopularSports translations
    popularSports: {
      title: "Suosituimmat lajit",
      time: "kerta",
      times: "kertaa",
    },

    // TopPerformers translations
    topPerformers: {
      title: "Viikon parhaat suorittajat",
    },

    // WeeklyInsights translations
    weeklyInsights: {
      title: "Kuluvan viikon tilastot",
      participant: "Osallistuja",
      weeklyProgress: "Viikon edistyminen",
      remainingWeeklyDailyTarget: "Loppuviikon päiväkohtainen tavoite",
    },
  } satisfies ThemeTranslations,
};