import { ActionType } from "typesafe-actions";
import { E_ApplicationActionConstants } from "../types";
import { T_ResponseError } from "../types";
export declare const applicationActions: {
    applicationInitializer: import("typesafe-actions").PayloadActionCreator<E_ApplicationActionConstants.GET_APPLICATION_INITIALIZEER, import("../types/application").T_Config>;
    applicationTrigger: import("typesafe-actions").EmptyActionCreator<E_ApplicationActionConstants.GET_APPLICATION_TRIGGER>;
    applicationSuccess: import("typesafe-actions").PayloadActionCreator<E_ApplicationActionConstants.GET_APPLICATION_SUCCESS, {
        id?: string;
        reference?: string;
        applicationChannel: "PHONE" | "BROKER" | "LETTER" | "WEB";
        applicationState?: import("packages/api-definitions/src").components["schemas"]["SMEApplicationState"];
        appliedProductId: string;
        appliedOfferId?: string;
        smeId: string;
        externalReference?: string;
        createDate?: string;
        updateDate?: string;
        desiredAmount: number;
        desiredPaybackTime?: number;
        loanReason?: "EXPANSION" | "INVENTORY" | "CASHFLOW" | "EQUIPMENT" | "REFINANCING" | "NONE";
        loanReasonText?: string;
        notificationEmail?: string;
        notificationMobileNumber?: string;
        downgradeAccepted?: boolean;
        preferredDueDay?: number;
        applicationComments?: string[];
        approvedAmount?: number;
        approvedPaybackTime?: number;
        decisionComment?: string;
        riskClass?: "LOW" | "NORMAL" | "HIGH";
        riskClassComment?: string;
        preferredDisbursementAccount?: import("packages/api-definitions/src").components["schemas"]["DisbursementAccountForSME"];
        manualDeltaInterestRate?: number;
        startupFee?: number;
        serviceFee?: number;
        statementChannel?: "PAPER" | "ELECTRONIC_EMAIL_NOTIFICATION" | "ELECTRONIC_SMS_NOTIFICATION" | "ELECTRONIC_NO_NOTIFICATION";
        statusUpdateDate?: string;
        assignedUser?: string;
        promissoryNoteSignedCheck?: boolean;
        promissoryNoteVersionId?: string;
        systemDeltaInterestRate?: number;
        accountId?: string;
        reservedAccountNumber?: string;
        actualDecision?: "APPROVED" | "REJECTED" | "INCOMPLETE" | "REFERRAL";
        suggestion?: "APPROVED" | "REJECTED" | "INCOMPLETE" | "REFERRAL";
        rejectReasonCode?: string;
        rejectReasonText?: string;
        extras?: {
            [key: string]: string | undefined;
        };
        documents?: import("packages/api-definitions/src").components["schemas"]["LoanDocumentBO"];
        preconditions?: import("packages/api-definitions/src").components["schemas"]["PreconditionResponse"];
        applicationCancelReasonType?: "MISINFORMATION" | "FRAUD_ATTEMPT" | "CUSTOMER_DECLINED_OFFER" | "OTHER_REASON";
        decisionMessage?: import("packages/api-definitions/src").components["schemas"]["DecisionMessageForSME"];
        credits?: import("packages/api-definitions/src").components["schemas"]["CreditV8ResponseBO"][];
        agreementSignatories?: import("packages/api-definitions/src").components["schemas"]["AgreementSignatoriesResponseBO"][];
        applicationCategory?: "NEW" | "TOP_UP";
        guarantees?: import("packages/api-definitions/src").components["schemas"]["GuaranteeV8Response"][];
        productInterestRate?: number;
        totalInterestRate?: number;
        effectiveInterestRate?: number;
        monthlyCost?: number;
        externalPartyId?: string;
        externalPartyName?: string;
        administrativeAreaName?: string;
        salesPerson?: string;
    }>;
    applicationError: import("typesafe-actions").PayloadActionCreator<E_ApplicationActionConstants.GET_APPLICATION_ERROR, T_ResponseError>;
};
export type ApplicationAction = ActionType<typeof applicationActions>;
