import { ActionType } from "typesafe-actions";
import { E_CompanyActionConstants, T_ResponseError, T_UpdateBankAccountNumberPayload, T_UpdateCompanyInfoPayload } from "../types";
type T_SmeID = {
    smeId: string;
};
export declare const companyActions: {
    companyDataInitializer: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_DATA_INITIALIZEER, import("../types/company").T_Config>;
    getCompanyInfoTrigger: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_INFO_TRIGGER, T_SmeID>;
    getCompanyInfoSuccess: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_INFO_SUCCESS, {
        id?: string;
        organizationNumber: string;
        organizationCountryCode: string;
        companyName: string;
        companyType?: string;
        externalReference?: string;
        officialAddress?: import("packages/api-definitions/src").components["schemas"]["AddressForSMEV2"];
        createDate?: string;
        updateDate?: string;
        phone?: string;
        email?: string;
        web?: string;
        signatoriesText?: string;
        businessTypeCode?: string;
        businessTypeDescription?: string;
        taxClassification?: string;
        VAT?: boolean;
        VATId?: string;
        LEI?: string;
        employeeCount?: number;
        parentCompanyOrgNumber?: string;
        parentCompanyCountryCode?: string;
        groupMotherOrgNumber?: string;
        groupMotherCountryCode?: string;
        incorporationDate?: string;
        companyStatus?: "ACTIVE";
        riskClass?: "LOW" | "NORMAL" | "HIGH";
        riskClassComment?: string;
        signatories?: import("packages/api-definitions/src").components["schemas"]["SignatoriesV2"];
        dynamicFields?: import("packages/api-definitions/src").components["schemas"]["VPDynamicFields"];
        dynamicFieldsRef?: string;
        schemaMetadata?: import("packages/api-definitions/src").components["schemas"]["ViljaSchemaMetadata"];
    }>;
    updateCompanyInfoTrigger: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.UPDATE_COMPANY_INFO_TRIGGER, T_UpdateCompanyInfoPayload>;
    updateCompanyInfoSuccess: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.UPDATE_COMPANY_INFO_SUCCESS, T_UpdateCompanyInfoPayload>;
    updateBankAccountNumberTrigger: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.UPDATE_BANK_ACCOUNT_NUMBER_TRIGGER, T_UpdateBankAccountNumberPayload>;
    updateBankAccountNumberSuccess: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.UPDATE_BANK_ACCOUNT_NUMBER_SUCCESS, T_UpdateBankAccountNumberPayload>;
    getCompanyInfoError: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_INFO_ERROR, T_ResponseError>;
    getCompanyAccountsTrigger: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_ACCOUNTS_TRIGGER, T_SmeID>;
    getCompanyAccountsSuccess: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_ACCOUNTS_SUCCESS, {
        id?: string;
        organizationNumber: string;
        organizationCountryCode: string;
        companyName: string;
        companyType?: string;
        externalReference?: string;
        officialAddress?: import("packages/api-definitions/src").components["schemas"]["AddressForSMEV2"];
        createDate?: string;
        updateDate?: string;
        phone?: string;
        email?: string;
        web?: string;
        signatoriesText?: string;
        businessTypeCode?: string;
        businessTypeDescription?: string;
        taxClassification?: string;
        VAT?: boolean;
        VATId?: string;
        LEI?: string;
        employeeCount?: number;
        parentCompanyOrgNumber?: string;
        parentCompanyCountryCode?: string;
        groupMotherOrgNumber?: string;
        groupMotherCountryCode?: string;
        incorporationDate?: string;
        companyStatus?: "ACTIVE";
        riskClass?: "LOW" | "NORMAL" | "HIGH";
        riskClassComment?: string;
        signatories?: import("packages/api-definitions/src").components["schemas"]["SignatoriesV2"];
        dynamicFields?: import("packages/api-definitions/src").components["schemas"]["VPDynamicFields"];
        dynamicFieldsRef?: string;
        schemaMetadata?: import("packages/api-definitions/src").components["schemas"]["ViljaSchemaMetadata"];
    }>;
    getCompanyAccountsError: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_ACCOUNTS_ERROR, T_ResponseError>;
    getCompanyBoardMembersTrigger: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_BOARD_MEMBERS_TRIGGER, T_SmeID>;
    getCompanyBoardMembersSuccess: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_BOARD_MEMBERS_SUCCESS, {
        id?: string;
        organizationNumber: string;
        organizationCountryCode: string;
        companyName: string;
        companyType?: string;
        externalReference?: string;
        officialAddress?: import("packages/api-definitions/src").components["schemas"]["AddressForSMEV2"];
        createDate?: string;
        updateDate?: string;
        phone?: string;
        email?: string;
        web?: string;
        signatoriesText?: string;
        businessTypeCode?: string;
        businessTypeDescription?: string;
        taxClassification?: string;
        VAT?: boolean;
        VATId?: string;
        LEI?: string;
        employeeCount?: number;
        parentCompanyOrgNumber?: string;
        parentCompanyCountryCode?: string;
        groupMotherOrgNumber?: string;
        groupMotherCountryCode?: string;
        incorporationDate?: string;
        companyStatus?: "ACTIVE";
        riskClass?: "LOW" | "NORMAL" | "HIGH";
        riskClassComment?: string;
        signatories?: import("packages/api-definitions/src").components["schemas"]["SignatoriesV2"];
        dynamicFields?: import("packages/api-definitions/src").components["schemas"]["VPDynamicFields"];
        dynamicFieldsRef?: string;
        schemaMetadata?: import("packages/api-definitions/src").components["schemas"]["ViljaSchemaMetadata"];
    }>;
    getCompanyBoardMembersError: import("typesafe-actions").PayloadActionCreator<E_CompanyActionConstants.GET_COMPANY_BOARD_MEMBERS_ERROR, T_ResponseError>;
};
export type CompanyAction = ActionType<typeof companyActions>;
export {};
