export enum E_Routes {
    ROOT = "/",
    LANDING_PAGE = "/start/:uuid",
    KYC_LANDING_PAGE = "kyc/start/:uuid",
    START = "/start",
    APPLICATION = "/application",
    PREVIEW = "/preview",
    APPLICATION_UUID_NULL = "/application/null",
    APPLICATION_UUID = "/application/:uuid",
    AUTHENTICATE = "/authenticate",
    FORBIDDEN = "/forbidden",
    EXPIRED = "/expired",
    ERROR = "/error",
    THANK_YOU = "/thank-you",
    ALL_OTHERS = "*",
}
