"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.E_CompanyActionConstants = void 0;
var E_CompanyActionConstants;
(function (E_CompanyActionConstants) {
    E_CompanyActionConstants["GET_COMPANY_DATA_INITIALIZEER"] = "FEATURE/SME_COMPANY_DATA_INITIALIZEER";
    E_CompanyActionConstants["GET_COMPANY_INFO_TRIGGER"] = "FEATURE/SME_CUSTOMER/COMPANY_INFO_TRIGGER";
    E_CompanyActionConstants["GET_COMPANY_INFO_SUCCESS"] = "FEATURE/SME_CUSTOMER/COMPANY_INFO_SUCCESS";
    E_CompanyActionConstants["GET_COMPANY_INFO_ERROR"] = "FEATURE/SME_CUSTOMER/COMPANY_INFO_SUCCESS_ERROR";
    E_CompanyActionConstants["GET_COMPANY_ACCOUNTS_TRIGGER"] = "FEATURE/SME_CUSTOMER/COMPANY_ACCOUNTS_TRIGGER";
    E_CompanyActionConstants["GET_COMPANY_ACCOUNTS_SUCCESS"] = "FEATURE/SME_CUSTOMER/COMPANY_ACCOUNTS_SUCCESS";
    E_CompanyActionConstants["GET_COMPANY_ACCOUNTS_ERROR"] = "FEATURE/SME_CUSTOMER/COMPANY_ACCOUNTS_ERROR";
    E_CompanyActionConstants["GET_COMPANY_BOARD_MEMBERS_TRIGGER"] = "FEATURE/SME_CUSTOMER/COMPANY_BOARD_MEMBERS_TRIGGER";
    E_CompanyActionConstants["GET_COMPANY_BOARD_MEMBERS_SUCCESS"] = "FEATURE/SME_CUSTOMER/COMPANY_BOARD_MEMBERS_SUCCESS";
    E_CompanyActionConstants["UPDATE_COMPANY_INFO_TRIGGER"] = "FEATURE/SME_CUSTOMER/UPDATE_COMPANY_INFO_TRIGGER";
    E_CompanyActionConstants["UPDATE_COMPANY_INFO_SUCCESS"] = "FEATURE/SME_CUSTOMER/UPDATE_COMPANY_INFO_SUCCESS";
    E_CompanyActionConstants["UPDATE_BANK_ACCOUNT_NUMBER_TRIGGER"] = "FEATURE/SME_CUSTOMER/UPDATE_BANK_ACCOUNT_NUMBER_TRIGGER";
    E_CompanyActionConstants["UPDATE_BANK_ACCOUNT_NUMBER_SUCCESS"] = "FEATURE/SME_CUSTOMER/UPDATE_BANK_ACCOUNT_NUMBER_SUCCESS";
    E_CompanyActionConstants["UPDATE_COMPANY_BOARD_MEMBERS_TRIGGER"] = "FEATURE/SME_CUSTOMER/UPDATE_COMPANY_BOARD_MEMBERS_TRIGGER";
    E_CompanyActionConstants["UPDATE_COMPANY_BOARD_MEMBERS_SUCCESS"] = "FEATURE/SME_CUSTOMER/UPDATE_COMPANY_BOARD_MEMBERS_SUCCESS";
    E_CompanyActionConstants["GET_COMPANY_BOARD_MEMBERS_ERROR"] = "FEATURE/SME_CUSTOMER/COMPANY_BOARD_MEMBERS_ERROR";
})(E_CompanyActionConstants || (exports.E_CompanyActionConstants = E_CompanyActionConstants = {}));
//# sourceMappingURL=company.js.map