import { KycReducerState } from "../types/types";
import { KycAction } from "../actions/actions";
export declare const kycReducer: import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
    handlers: Record<import("../actions/actions").E_KycActionConstants.SHOW_MODAL | import("../actions/actions").E_KycActionConstants.HIDE_MODAL, (state: KycReducerState, action: KycAction) => KycReducerState>;
    handleAction: <TActionCreator extends (...args: any[]) => import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START> | import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS> | import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, THandledAction extends ReturnType<TActionCreator>, TOutputAction extends Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, THandledAction> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, THandledAction> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, THandledAction>>(singleOrMultipleCreatorsAndTypes: TActionCreator | TActionCreator[], reducer: (state: KycReducerState, action: THandledAction) => KycReducerState) => [TOutputAction] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
        handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
        handleAction: <TActionCreator_1 extends (...args: any[]) => TOutputAction, THandledAction_1 extends ReturnType<TActionCreator_1>, TOutputAction_1 extends Exclude<TOutputAction, THandledAction_1>>(singleOrMultipleCreatorsAndTypes: TActionCreator_1 | TActionCreator_1[], reducer: (state: KycReducerState, action: THandledAction_1) => KycReducerState) => [TOutputAction_1] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
            handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_1> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_1> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_1> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_1> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_1>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
            handleAction: <TActionCreator_2 extends (...args: any[]) => TOutputAction_1, THandledAction_2 extends ReturnType<TActionCreator_2>, TOutputAction_2 extends Exclude<TOutputAction_1, THandledAction_2>>(singleOrMultipleCreatorsAndTypes: TActionCreator_2 | TActionCreator_2[], reducer: (state: KycReducerState, action: THandledAction_2) => KycReducerState) => [TOutputAction_2] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_2> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_2> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_2> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_2> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_2>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                handleAction: <TActionCreator_3 extends (...args: any[]) => TOutputAction_2, THandledAction_3 extends ReturnType<TActionCreator_3>, TOutputAction_3 extends Exclude<TOutputAction_2, THandledAction_3>>(singleOrMultipleCreatorsAndTypes: TActionCreator_3 | TActionCreator_3[], reducer: (state: KycReducerState, action: THandledAction_3) => KycReducerState) => [TOutputAction_3] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                    handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_3> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_3> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_3> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_3> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_3>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                    handleAction: <TActionCreator_4 extends (...args: any[]) => TOutputAction_3, THandledAction_4 extends ReturnType<TActionCreator_4>, TOutputAction_4 extends Exclude<TOutputAction_3, THandledAction_4>>(singleOrMultipleCreatorsAndTypes: TActionCreator_4 | TActionCreator_4[], reducer: (state: KycReducerState, action: THandledAction_4) => KycReducerState) => [TOutputAction_4] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                        handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_4> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_4> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_4> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_4> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_4>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                        handleAction: <TActionCreator_5 extends (...args: any[]) => TOutputAction_4, THandledAction_5 extends ReturnType<TActionCreator_5>, TOutputAction_5 extends Exclude<TOutputAction_4, THandledAction_5>>(singleOrMultipleCreatorsAndTypes: TActionCreator_5 | TActionCreator_5[], reducer: (state: KycReducerState, action: THandledAction_5) => KycReducerState) => [TOutputAction_5] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                            handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_5> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_5> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_5> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_5> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_5>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                            handleAction: <TActionCreator_6 extends (...args: any[]) => TOutputAction_5, THandledAction_6 extends ReturnType<TActionCreator_6>, TOutputAction_6 extends Exclude<TOutputAction_5, THandledAction_6>>(singleOrMultipleCreatorsAndTypes: TActionCreator_6 | TActionCreator_6[], reducer: (state: KycReducerState, action: THandledAction_6) => KycReducerState) => [TOutputAction_6] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_6> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_6> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_6> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_6> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_6>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                                handleAction: <TActionCreator_7 extends (...args: any[]) => TOutputAction_6, THandledAction_7 extends ReturnType<TActionCreator_7>, TOutputAction_7 extends Exclude<TOutputAction_6, THandledAction_7>>(singleOrMultipleCreatorsAndTypes: TActionCreator_7 | TActionCreator_7[], reducer: (state: KycReducerState, action: THandledAction_7) => KycReducerState) => [TOutputAction_7] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                    handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_7> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_7> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_7> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_7> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_7>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                                    handleAction: <TActionCreator_8 extends (...args: any[]) => TOutputAction_7, THandledAction_8 extends ReturnType<TActionCreator_8>, TOutputAction_8 extends Exclude<TOutputAction_7, THandledAction_8>>(singleOrMultipleCreatorsAndTypes: TActionCreator_8 | TActionCreator_8[], reducer: (state: KycReducerState, action: THandledAction_8) => KycReducerState) => [TOutputAction_8] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                        handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_8> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_8> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_8> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_8> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_8>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                                        handleAction: <TActionCreator_9 extends (...args: any[]) => TOutputAction_8, THandledAction_9 extends ReturnType<TActionCreator_9>, TOutputAction_9 extends Exclude<TOutputAction_8, THandledAction_9>>(singleOrMultipleCreatorsAndTypes: TActionCreator_9 | TActionCreator_9[], reducer: (state: KycReducerState, action: THandledAction_9) => KycReducerState) => [TOutputAction_9] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                            handlers: Record<(Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.SHOW_MODAL>, TOutputAction_9> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.HIDE_MODAL>, TOutputAction_9> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_START>, TOutputAction_9> | Exclude<import("typesafe-actions").EmptyAction<import("../actions/actions").E_KycActionConstants.VALIDATION_SUCCESS>, TOutputAction_9> | Exclude<import("typesafe-actions").PayloadAction<import("../actions/actions").E_KycActionConstants.VALIDATION_FAILED, import("../types/types").T_ResponseError>, TOutputAction_9>)["type"], (state: KycReducerState, action: KycAction) => KycReducerState>;
                                            handleAction: <TActionCreator_10 extends (...args: any[]) => TOutputAction_9, THandledAction_10 extends ReturnType<TActionCreator_10>, TOutputAction_10 extends Exclude<TOutputAction_9, THandledAction_10>>(singleOrMultipleCreatorsAndTypes: TActionCreator_10 | TActionCreator_10[], reducer: (state: KycReducerState, action: THandledAction_10) => KycReducerState) => [TOutputAction_10] extends [import("typesafe-actions").Action] ? import("typesafe-actions").Reducer<KycReducerState, KycAction> & any : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                                handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                                            };
                                        } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                            handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                                        };
                                    } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                        handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                                    };
                                } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                    handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                                };
                            } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                                handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                            };
                        } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                            handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                        };
                    } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                        handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                    };
                } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                    handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
                };
            } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
                handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
            };
        } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
            handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
        };
    } : import("typesafe-actions").Reducer<KycReducerState, KycAction> & {
        handlers: Record<import("../actions/actions").E_KycActionConstants, (state: KycReducerState, action: KycAction) => KycReducerState>;
    };
};
