import { T_ExistingCustomerApplication } from "packages/feature-sme-customer/src/types";
import { ApplicationChannel, ApplicationState, KycData } from "../src/types";
export declare const isApplicationStatusValid: (applicationChannel: ApplicationChannel, applicationState: ApplicationState) => boolean;
export declare const hasKycBeenFilled: (kycUpdatedDate: string | undefined | null) => boolean;
export declare const getDaysSinceKycUpdate: (kycUpdatedDate: string) => number;
export declare const isKycDeadlinePassed: (kycUpdatedDate: string | undefined | null, deadlineDays: number) => boolean;
export declare const getKycDeadlineDate: (deadlineDays: number) => Date;
export declare const formatDeadlineDate: (date: Date) => string;
export declare const getKycDataFromApplication: (application: T_ExistingCustomerApplication | undefined) => KycData;
export declare const getKycDeadlineDays: () => number;
