export const sportsOptions = [
  "Juoksu",
  "Sali", 
  "Tennis",
  "Pyöräily",
  "Hiihto",
  "Uinti",
  "Crossfit",
  "Tribe",
  "Ryhmä, pump",
  "Ryhmä, dance",
  "Ryhmä, combat",
  "Spinning",
  "Squash",
  "Sulkapallo",
  "Padel",
  "Jooga",
  "Liikkuvuus",
  "Golf",
  "Ryhmä, HIIT",
  "Kehonpainotreeni",
  "Jalkapallo",
  "Jääkiekko",
  "Kamppailulaji",
  "Muu(100km/h)",
  "Muu(50km/h)",
];

export const bonusOptions = [
  { label: 'Ei bonusta', value: null },
  { label: 'Juhlapäivä (2x km)', value: 'juhlapäivä' },
  { label: 'Enemmän kuin kolme urheilee yhdessä (1.5x km)', value: 'enemmän kuin kolme urheilee yhdessä' },
  { label: 'Kaikki yhdessä (3x km)', value: 'kaikki yhdessä' },
];