import { SystemStyleObject } from "@styled-system/css";
export declare function frontPageRootStyles(): SystemStyleObject;
export declare function accountCollectionMainContainer(): SystemStyleObject;
export declare function accountCollectionInfoBox(): SystemStyleObject;
export declare function accountCollectionInfoHeading(): SystemStyleObject;
export declare function accountCollectionInfoText(): SystemStyleObject;
export declare function accountCollectionEmailLink(): SystemStyleObject;
export declare function collectionInfoItemContainer(): SystemStyleObject;
export declare function creditAgreementContainer(): SystemStyleObject;
export declare function downloadButtonContainer(): SystemStyleObject;
export declare function creditAgreementText(): SystemStyleObject;
export declare function mainContentContainer(): SystemStyleObject;
export declare function nostoContainer(): SystemStyleObject;
export declare function nostoImage(): SystemStyleObject;
export declare function nostoText(): SystemStyleObject;
export declare function loanInfoContainer(): SystemStyleObject;
export declare function loanInfoTitle(): SystemStyleObject;
export declare function remainingCreditWrapper(): SystemStyleObject;
export declare function remainingCreditText(): SystemStyleObject;
export declare function remainingCreditAmount(): SystemStyleObject;
export declare function balanceContainer(): SystemStyleObject;
export declare function percentageContainer(): SystemStyleObject;
export declare function creditWrapper(): SystemStyleObject;
export declare function creditUsed(): SystemStyleObject;
export declare function creditTotal(): SystemStyleObject;
export declare function creditText(): SystemStyleObject;
export declare function balanceInfo(): SystemStyleObject;
export declare function newsContainer(): SystemStyleObject;
export declare function creditRaiseContainer(): SystemStyleObject;
export declare function creditRaiseTitle(): SystemStyleObject;
export declare function creditRaiseWrapper(): SystemStyleObject;
export declare function creditRaiseInputColumn(): SystemStyleObject;
export declare function creditRaiseInputSectionWrapper(): SystemStyleObject;
export declare function creditIncreaseInputRow(): SystemStyleObject;
export declare function creditRaiseInput(): SystemStyleObject;
export declare function creditRaiseInputWrapper(): SystemStyleObject;
export declare function creditRaiseInputError(): SystemStyleObject;
export declare function creditRaiseEuroSign(props?: {
    marginRight?: string | number;
    marginLeft?: string | number;
    order?: number;
}): SystemStyleObject;
export declare function creditRaiseInfoColumn(): SystemStyleObject;
export declare function creditRaiseText({ textAlign }: {
    textAlign: any;
}): SystemStyleObject;
export declare function rulesContainer(): SystemStyleObject;
export declare function errorMessage(): SystemStyleObject;
export declare function notEligibleReasonContainer(): SystemStyleObject;
export declare function withdrawButton(props?: any): SystemStyleObject;
export declare function withdrawDisabledButton(props?: any): SystemStyleObject;
export declare function buttonInfo(): SystemStyleObject;
