import { SystemStyleObject } from "@styled-system/css";
export declare function NoTopUpPageRootStyles(): SystemStyleObject;
export declare function NoTopUpPageTitleContainer(): SystemStyleObject;
export declare function NoTopUpPageTitleText(): SystemStyleObject;
export declare function NoTopUpPageContainer(): SystemStyleObject;
export declare function NoTopUpPageText(): SystemStyleObject;
export declare function containerInfo(): SystemStyleObject;
export declare function containerInfoList(): SystemStyleObject;
export declare function NoTopUpPageLink(): SystemStyleObject;
export declare function NoTopUpPageContactInfo(): SystemStyleObject;
export declare function NoTopUpPageContent(): SystemStyleObject;
export declare function NoTopUpPageTitle(): SystemStyleObject;
