import { SystemStyleObject } from "@styled-system/css";
import { T_StartPageBankProperties } from "../general";
export type PageNoticeProps = {
    label: string;
};
export declare function startPageNotice(): SystemStyleObject;
export declare function startPageNoticeContainer(props: PageNoticeProps): SystemStyleObject;
export declare function startPageRootStyles(): SystemStyleObject;
export declare function startPagePathDivider(): SystemStyleObject;
export declare function startPagePathDividerText(): SystemStyleObject;
export declare function startPageApplicationPath(): SystemStyleObject;
export declare function startPagePathHeading(): SystemStyleObject;
export declare function startPagePathText(): SystemStyleObject;
export declare function startPageLoginPath(): SystemStyleObject;
export declare function startPageNoticeListContainer(): SystemStyleObject;
export declare function startPageContainer(): SystemStyleObject;
export declare function bankIdContainer(): SystemStyleObject;
export declare function startPageContentStyles(): SystemStyleObject;
export declare function startPageBank(): SystemStyleObject;
export declare function startPageBankContainer(properties: T_StartPageBankProperties): SystemStyleObject;
