import { SystemStyleObject } from "@styled-system/css";
export declare function userPageRootStyles(): SystemStyleObject;
export declare function userPageContainer(): SystemStyleObject;
export declare function userPageFlexContainer(): SystemStyleObject;
export declare function userPageColumn(): SystemStyleObject;
export declare function userPageTextGroup(): SystemStyleObject;
export declare function userPageTextButtonGroup(): SystemStyleObject;
export declare function userPageButtonGroup(): SystemStyleObject;
export declare function userPageAddressColumn(): SystemStyleObject;
export declare function formError(): SystemStyleObject;
export declare function inputContainer(): SystemStyleObject;
export declare function textField(): SystemStyleObject;
export declare function titleAndEditButtonContainer(): SystemStyleObject;
