import { E_ApplicationActionConstants, T_ApplicationApiResponse, T_Config } from "../types";
export declare function watchSmeApplicationTrigger(): Generator<import("redux-saga/effects").ForkEffect<never>, void, unknown>;
export declare function handleApplicationTrigger(): Generator<import("redux-saga/effects").SelectEffect | import("redux-saga/effects").PutEffect<import("typesafe-actions").PayloadAction<E_ApplicationActionConstants.GET_APPLICATION_ERROR, import("../types").T_ResponseError>> | import("redux-saga/effects").CallEffect<T_ApplicationApiResponse> | import("redux-saga/effects").PutEffect<import("typesafe-actions").PayloadAction<import("../types").E_CompanyActionConstants.GET_COMPANY_INFO_TRIGGER, {
    smeId: string;
}>> | import("redux-saga/effects").PutEffect<import("typesafe-actions").PayloadAction<E_ApplicationActionConstants.GET_APPLICATION_SUCCESS, T_ApplicationApiResponse>>, void, T_Config & {
    id?: string;
    reference?: string;
    applicationChannel: "PHONE" | "BROKER" | "LETTER" | "WEB";
    applicationState?: import("packages/api-definitions/src").components["schemas"]["SMEApplicationState"];
    appliedProductId: string;
    appliedOfferId?: string;
    smeId: string;
    externalReference?: string;
    createDate?: string;
    updateDate?: string;
    desiredAmount: number;
    desiredPaybackTime?: number;
    loanReason?: "EXPANSION" | "INVENTORY" | "CASHFLOW" | "EQUIPMENT" | "REFINANCING" | "NONE";
    loanReasonText?: string;
    notificationEmail?: string;
    notificationMobileNumber?: string;
    downgradeAccepted?: boolean;
    preferredDueDay?: number;
    applicationComments?: string[];
    approvedAmount?: number;
    approvedPaybackTime?: number;
    decisionComment?: string;
    riskClass?: "LOW" | "NORMAL" | "HIGH";
    riskClassComment?: string;
    preferredDisbursementAccount?: import("packages/api-definitions/src").components["schemas"]["DisbursementAccountForSME"];
    manualDeltaInterestRate?: number;
    startupFee?: number;
    serviceFee?: number;
    statementChannel?: "PAPER" | "ELECTRONIC_EMAIL_NOTIFICATION" | "ELECTRONIC_SMS_NOTIFICATION" | "ELECTRONIC_NO_NOTIFICATION";
    statusUpdateDate?: string;
    assignedUser?: string;
    promissoryNoteSignedCheck?: boolean;
    promissoryNoteVersionId?: string;
    systemDeltaInterestRate?: number;
    accountId?: string;
    reservedAccountNumber?: string;
    actualDecision?: "APPROVED" | "REJECTED" | "INCOMPLETE" | "REFERRAL";
    suggestion?: "APPROVED" | "REJECTED" | "INCOMPLETE" | "REFERRAL";
    rejectReasonCode?: string;
    rejectReasonText?: string;
    extras?: {
        [key: string]: string | undefined;
    };
    documents?: import("packages/api-definitions/src").components["schemas"]["LoanDocumentBO"];
    preconditions?: import("packages/api-definitions/src").components["schemas"]["PreconditionResponse"];
    applicationCancelReasonType?: "MISINFORMATION" | "FRAUD_ATTEMPT" | "CUSTOMER_DECLINED_OFFER" | "OTHER_REASON";
    decisionMessage?: import("packages/api-definitions/src").components["schemas"]["DecisionMessageForSME"];
    credits?: import("packages/api-definitions/src").components["schemas"]["CreditV8ResponseBO"][];
    agreementSignatories?: import("packages/api-definitions/src").components["schemas"]["AgreementSignatoriesResponseBO"][];
    applicationCategory?: "NEW" | "TOP_UP";
    guarantees?: import("packages/api-definitions/src").components["schemas"]["GuaranteeV8Response"][];
    productInterestRate?: number;
    totalInterestRate?: number;
    effectiveInterestRate?: number;
    monthlyCost?: number;
    externalPartyId?: string;
    externalPartyName?: string;
    administrativeAreaName?: string;
    salesPerson?: string;
} & {
    dynamicFields: import("../types/application").T_ApplicationDynamicFields;
}>;
